#!/bin/bash

# Simplistic Calculator - App Store Setup Script
# This script opens Xcode and provides next steps

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  📱 Simplistic Calculator - App Store Setup"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Already Completed:"
echo "  • Professional calculator icon created"
echo "  • All 15 iOS icon sizes generated"
echo "  • Privacy manifest file created"
echo "  • Bundle ID updated to: com.morriswong.calculator"
echo "  • Support website ready with your email"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 NEXT STEPS (Manual - Required for App Store):"
echo ""
echo "1. ⚠️  REGISTER BUNDLE ID IN APPLE DEVELOPER PORTAL"
echo "   • Go to: https://developer.apple.com/account/resources/identifiers/list"
echo "   • Click '+' → App IDs → App"
echo "   • Description: Simplistic Calculator"
echo "   • Bundle ID: com.morriswong.calculator"
echo "   • Click Register"
echo ""
echo "2. 📱 ADD PRIVACY FILE IN XCODE (Opening now...)"
echo "   • Xcode will open automatically"
echo "   • Right-click 'Runner' folder (in left panel)"
echo "   • Select 'Add Files to Runner...'"
echo "   • Navigate to: ios/Runner/PrivacyInfo.xcprivacy"
echo "   • ✓ Check 'Copy items if needed'"
echo "   • ✓ Select 'Runner' target"
echo "   • Click 'Add'"
echo ""
echo "3. 🌐 DEPLOY SUPPORT WEBSITE"
echo "   Option A - GitHub Pages (Quick):"
echo "     • Create repo: simplistic-calculator-support"
echo "     • Upload: support/index.html as index.html"
echo "     • Enable GitHub Pages in repo settings"
echo "     • URL will be: https://morriswong.github.io/simplistic-calculator-support/"
echo ""
echo "   Option B - Use this repo (if public):"
echo "     • Host support/index.html directly from this repo"
echo ""
echo "4. 📦 BUILD & ARCHIVE IN XCODE"
echo "   • Select 'Any iOS Device (arm64)' from device dropdown"
echo "   • Product → Clean Build Folder"
echo "   • Product → Archive (wait 2-5 minutes)"
echo ""
echo "5. 🚀 UPLOAD TO APP STORE CONNECT"
echo "   • In Archives window → Distribute App"
echo "   • Select 'App Store Connect' → Upload"
echo ""
echo "6. 📝 COMPLETE APP STORE METADATA"
echo "   • Go to: https://appstoreconnect.apple.com"
echo "   • Create new app with bundle ID: com.morriswong.calculator"
echo "   • Fill in description (see PUBLISHING_GUIDE.md)"
echo "   • Upload screenshots from Simulator"
echo "   • Set privacy: No data collection"
echo "   • Submit for review"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📖 FULL GUIDE: See PUBLISHING_GUIDE.md for detailed instructions"
echo ""
echo "🔧 FILES TO REFERENCE:"
echo "  • App Icon: assets/icon.png (1024x1024)"
echo "  • Privacy File: ios/Runner/PrivacyInfo.xcprivacy"
echo "  • Support Site: support/index.html"
echo "  • Bundle ID: com.morriswong.calculator"
echo "  • Support Email: morriswch@gmail.com"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Opening Xcode workspace in 3 seconds..."
sleep 3

# Open Xcode
open ios/Runner.xcworkspace

echo ""
echo "✅ Xcode opened! Follow steps 2-6 above to complete App Store submission."
echo ""
echo "💡 TIP: Keep this terminal window open for reference"
echo ""
